version: '3.9'
services:
  database:
    container_name: acapra-database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql2/data